# language: en
# Overview: docs/spec/layout/layout.md
# SPEC §2 (orientation pattern, map symmetry), §11 items 4, 29

Feature: Layout edge cases — parity, degenerate parameters, and the skew check
  As the renderer
  I want the silhouette to depend on triangle parity and nothing else
  So that retuning the artwork cannot change which arrow a pixel belongs to

  Background:
    Given a tiling generated by makeTiling with no arguments
    And a window of radius 4 grown from its seed point

  Rule: Up and down triangles must twist oppositely

    The finding this packet exists to record. Same-direction twisting still
    tiles, so no gap-or-overlap test catches it — it just silently produces a
    symmetric zigzag with two points and no arrowhead.

    Scenario: Opposite twist makes the tile asymmetric
      Given a layout whose up and down triangles twist oppositely
      When I request the polygon for any arrow
      Then the polygon is not centrally symmetric about its arrow's midpoint

    Scenario: Same-direction twist makes the tile symmetric
      Given a layout whose up and down triangles twist the same way
      When I request the polygon for any arrow
      Then the polygon is centrally symmetric about its arrow's midpoint
      # Recorded as the WRONG configuration, kept as a scenario because it is
      # indistinguishable from the right one by area, vertex count or tiling.

    Scenario: Both twist conventions tile the plane
      When I compute tile areas under each twist convention
      Then every tile is √3/6 under both
      # Which is exactly why this needs its own assertion: tiling does not
      # discriminate, so only symmetry does.

  Rule: The silhouette parameters are tunable without moving a tile

    SPEC §7 imposes the same discipline on spawner force: values are data, and no
    logic branches on them.

    Scenario Outline: Changing twist and bend never changes which arrows exist
      Given a layout at twist <twist> degrees and bend <bend> percent
      When I request a polygon for every arrow in the window
      Then every arrow still yields exactly 1 polygon
      And every tile area is still √3/6

      Examples:
        | twist | bend | note                          |
        | 0     | 36   | rhombus, the debugging view   |
        | 87    | 36   | the measured POC values       |
        | 100   | 20   | a deeper, thinner arm         |
        | -87   | 36   | mirrored handedness           |

    Scenario Outline: The silhouette varies continuously in <parameter>
      When I sweep <parameter> across its range in small steps
      Then no step moves any polygon vertex more than a small distance
      # This is how "no method branches on a particular value" becomes testable.
      # A threshold — `if twist is 87` — puts a jump in the map from parameter to
      # polygon, and nothing else does. Fixed-value tests cannot see it.

      Examples:
        | parameter |
        | twist     |
        | bend      |

  Rule: Layout is translation-invariant, because the board is

    SPEC §11 item 4: the board is unbounded and every cell is like every other.
    There is no canonical cell, no fundamental domain and nothing to clip
    against, so the tile at one cell is the tile at any other, moved.

    Scenario Outline: The same arrow direction is the same shape everywhere
      Given the arrow from cell <cell> along direction 0
      And the arrow from cell (0, 0) along direction 0
      When I request both polygons
      Then the two polygons are congruent by translation

      Examples:
        | cell           | note                        |
        | (5, 0)         | a nearby cell                |
        | (-3, 7)        | negative coordinates         |
        | (400, 400)     | far outside any window       |

    Scenario: Layout clips nothing
      When I request the polygon for an arrow 400 cells from the origin
      Then its vertices are 400 cells from the origin
      And the parameters layout accepts name no scale, offset or bounds
      # Clamping would still return eight plausible vertices, so the distance is
      # what catches it, not the vertex count.

  Rule: Layout is the only check on the out-direction constant

    A set of out-directions summing to zero but not 120 degrees apart passes
    every GeometryPort assertion. Only geometry catches it.

    Scenario: The three tiles around a vertex are congruent by 120 degree rotation
      Given any vertex on the board
      When I request the polygons of its 3 bordering arrows
      Then each is the previous one rotated 120 degrees about that vertex's centre

    Scenario: A skewed out-direction set fails the rotation check
      Given a layout built from out-directions that sum to zero but sit at 0, 60 and 210 degrees
      When I request the polygons of a vertex's 3 bordering arrows
      Then they are not congruent by 120 degree rotation
      # The graph is isomorphic and every rule behaves identically on it, so this
      # scenario is the only place the mistake is detectable.

  Rule: Degenerate parameters are refused

    Scenario Outline: A bend outside the open unit interval is rejected
      When I build a layout at twist 87 degrees and bend <bend> percent
      Then the layout raises a contract violation

      Examples:
        | bend | why                                          |
        | 0    | the spoke collapses to the triangle centre    |
        | 100  | the spoke collapses onto the corner           |
        | -10  | a bend is a fraction of the way out           |
        | 140  | past the corner, so tiles would self-intersect |
