# language: en
# Overview: docs/spec/tiling/tiling.md
# SPEC §2 (the board is unbounded, orientation pattern), §11 items 4, 16, 29

Feature: Tiling edge cases — unboundedness, degenerate windows, and the skew trap
  As the rules core
  I want an edgeless board, degenerate queries refused, and the skew caught
  So that no rule ever has to special-case where it is on the board

  Background:
    Given a tiling generated by makeTiling with no arguments

  Rule: The board has no edge, in any direction

    SPEC §11 item 4 made the board unbounded. There is no seam, no rim and no
    size, so there is nothing for a rule to special-case and nothing for the port
    to report. Walking far enough in any direction is uneventful, which is the
    whole claim.

    Scenario Outline: Walking a long way never runs out of board
      Given the point at cell (0, 0)
      When I follow out-direction <d> for 10000 steps
      Then every step lands on a point with 3 in-arrows and 3 out-arrows
      And no step is refused

      Examples:
        | d | direction   |
        | 0 | east        |
        | 1 | up-left     |
        | 2 | down-left   |

    Scenario: No query reveals the board's size or coordinates
      When I inspect everything the GeometryPort exposes
      Then no method returns a lattice coordinate
      And no method returns a board dimension
      And no method reports whether a point is near an edge

    Scenario: A zigzag of two out-directions is a straight line in the third
      Given the point at cell (0, 0)
      When I alternate out-direction 1 and out-direction 2 for 8 steps
      Then I have moved exactly 4 steps along the reverse of out-direction 0
      # Because the three out-directions sum to zero, any two of them compose to
      # the reverse of the third. No drift, and nothing to do with wrapping.

  Rule: A degenerate window is refused

    The board has no size left to validate, so the window radius is the only
    input the generator can be given wrongly.

    Scenario Outline: A radius that is not a whole non-negative number is rejected
      When I grow a window of radius <radius>
      Then the generator raises a contract violation

      Examples:
        | radius   | why                                       |
        | -1       | a ball cannot have negative extent         |
        | 1.5      | a graph distance is a whole number         |
        | NaN      | not a number at all                        |
        | Infinity | the board is unbounded; the query must not be |

    Scenario: A window of radius zero is exactly its centre
      When I grow a window of radius 0 from the seed point
      Then its points are exactly the seed point
      And its arrows are the 6 arrows incident to it
      And its vertices are the 6 vertices those arrows flank

    Scenario: A very large window is still answerable
      When I grow a window of radius 40
      Then it holds exactly 4921 points
      And the query completes without precomputing the board
      # 3r² + 3r + 1 at r = 40. The point is that size is bounded by the ASK,
      # never by the board.

  Rule: Girth 3, and each minimal cycle holds exactly one spawner

    SPEC §11 item 16, resolved and load-bearing: this is what makes the atomic
    unit of conquest and the atomic unit of value the same object. Unbounded, it
    is a purely local property and holds everywhere without a size condition —
    which is what removed the old 4×4 floor along with the wrap that caused it.

    Scenario: No cycle is shorter than three
      When I enumerate every arrow in a window
      Then no arrow's origin equals its target
      And no two-arrow path returns to where it started

    Scenario: Every directed 3-cycle encloses exactly one vertex
      When I enumerate every directed 3-cycle in a window
      Then the three arrows of each cycle share exactly 1 flank vertex

    Scenario: Every vertex is enclosed by exactly one minimal cycle
      When I enumerate every directed 3-cycle in a window
      Then no vertex is enclosed by two different cycles
      And every vertex flanked by a cycle's arrows is enclosed by that one cycle

    Scenario: Enumerating cycles counts each once, not once per rotation
      When I enumerate every directed 3-cycle in a window
      Then a cycle discoverable from each of its 3 arrows appears once
      # Left unstated, this makes every vertex look like it owns three cycles and
      # the previous scenario can never pass.

  Rule: The out-directions must be 120 degrees apart, not merely sum to zero

    The trap this packet exists to document. {(1,0), (0,1), (-1,-1)} sums to zero
    and passes EVERY assertion above — it is the same graph under a change of
    basis — while sitting at 0/60/210 degrees and rendering skewed. No rule can
    tell the difference; only layout can.

    Scenario: The three out-directions sum to zero
      When I sum the three out-directions in lattice coordinates
      Then the result is the zero vector

    Scenario: The three out-directions are 120 degrees apart in world space
      When I convert the three out-directions to world space
      Then their angles are 0, 120 and 240 degrees
      And no two of them are 60 degrees apart

  Rule: The grain constrains which symmetries are usable

    SPEC §2, map symmetry. Setup (P09) needs an involution to place two players
    fairly, and the obvious one does not exist. Asserted here because it is a
    property of the generated lattice, and because getting it wrong would hand
    one player a board running backwards — a bug no rules test could see.

    Scenario: The 120 degree rotation preserves the grain
      When I rotate every out-direction by 120 degrees
      Then the set of out-directions is unchanged

    Scenario: The 180 degree rotation reverses the grain
      When I map every out-direction through (i,j) to (-i,-j)
      Then no image is an out-direction
      And every image is an in-direction
      # So central inversion is an anti-automorphism, not a symmetry.

    Scenario: The reflection preserves the grain and is an involution
      When I map every out-direction through (i,j) to (i+j,-j)
      Then the set of out-directions is unchanged
      And applying the map twice is the identity
      # This is the one two-player setup can use.

  Rule: Foreign and malformed identifiers fail loudly

    Fixture boards (P02) and the generated tiling coexist in one test run. An id
    minted against one must never silently resolve against the other.

    Scenario Outline: A query given an identifier from another board raises
      Given an identifier minted against a different board
      When I call <query> with it
      Then the generator raises a contract violation

      Examples:
        | query          |
        | out-arrows     |
        | in-arrows      |
        | origin         |
        | target         |
        | flank-vertices |
        | border-arrows  |
        | window         |

    Scenario: Asking for the slot of an arrow that is not at a point raises
      Given the point at cell (0, 0)
      And an arrow that is neither an in-arrow nor an out-arrow of it
      When I ask for that arrow's slot at that point
      Then the generator raises a contract violation
