# language: en
# Overview: docs/spec/tiling/tiling.md
# SPEC §2 (the board, formal definition, the board is unbounded), §7 (specials on vertices)

Feature: Generating the arrow tiling
  As the renderer and the rules core
  I want the unbounded oriented lattice behind a GeometryPort
  So that the real tiling exists without anything having to be traced, measured or sized

  Background:
    Given a tiling generated by makeTiling with no arguments

  Rule: The counts close at 3 : 1 : 2

    SPEC §2 derives these from incidence rather than asserting them, so a
    generator that gets one wrong has a structural bug and not an off-by-one.

    The board is unbounded (§11 item 4), so these are densities and each is
    asserted over a window. A ball of radius r on the triangular lattice holds
    the centred hexagonal number of points, which makes the expected count exact
    rather than approximate.

    Scenario Outline: A window of radius r holds 3r² + 3r + 1 points
      When I grow a window of radius <r> from the seed point
      Then it holds exactly <points> points
      And exactly 3 times that many arrows originate at those points

      Examples:
        | r | points | note                          |
        | 0 | 1      | the centre alone              |
        | 1 | 7      | the centre and its neighbours |
        | 2 | 19     |                               |
        | 3 | 37     |                               |
        | 4 | 61     | the suite's default radius    |

    Scenario: Every point lies on exactly six minimal cycles
      When I enumerate every point in a window
      Then exactly 6 directed 3-cycles pass through each
      # Three points per cycle, so cycles are twice the points, so vertices are
      # twice the points. The 2:1 half of the ratio, without a global count.

  Rule: Adjacency follows the three out-directions

    Scenario: Every point has three out-arrows and three in-arrows
      When I enumerate every point in a window
      Then each point has exactly 3 out-arrows
      And each point has exactly 3 in-arrows

    Scenario: An arrow runs from its origin cell along one out-direction
      Given the point at cell (2, 2)
      When I take its out-arrow along direction 0
      Then that arrow's origin is the point at cell (2, 2)
      And that arrow's target is the point at cell (3, 2)

    Scenario: Adjacency agrees with arrow endpoints
      When I enumerate every arrow in a window
      Then each arrow is among the out-arrows of its origin
      And each arrow is among the in-arrows of its target

  Rule: A cell owns two triangles, and they are its spawner vertices

    SPEC §2: triangle centres are the spawner vertices, two per lattice point.
    An arrow's flanks are always one up and one down — which is why §7's cap of
    two feed slots per arrow needs no rule to enforce it.

    Scenario: Every arrow flanks one up-triangle and one down-triangle
      When I enumerate every arrow in a window
      Then each arrow has exactly 2 flank vertices
      And exactly 1 of them is an up-triangle
      And exactly 1 of them is a down-triangle

    Scenario: Every vertex borders exactly three arrows
      When I enumerate every vertex in a window
      Then each vertex has exactly 3 bordering arrows

    Scenario: Flank and border are mutually inverse
      When I enumerate every arrow and every vertex in a window
      Then each arrow appears among the bordering arrows of both its flanks
      And each vertex appears among the flanks of all three arrows it borders

  Rule: Slots alternate in and out around a point

    SPEC §11 item 29 makes alternation a conformance requirement of every board.
    The PHASE is free, and this generator happens to put in-arrows on the odd
    slots — which is exactly the fact item 29 forbids anything depending on.

    Scenario: A point's six arrows take six distinct slots
      When I enumerate every point in a window
      Then that point's 3 in-arrows and 3 out-arrows occupy 6 distinct slots

    Scenario: In-arrows and out-arrows alternate around a point
      When I enumerate every point in a window
      Then no two adjacent slots hold arrows of the same direction

    Scenario: A slot query is stable
      Given the point at cell (1, 3) and one of its out-arrows
      When I ask for that arrow's slot twice
      Then both answers are the same slot

  Rule: The board is unbounded and has no rim

    SPEC §11 item 4. Balance holds at every point because there is no point that
    is special, and adjacency is total: no cell is too far away to answer for.

    Scenario: Every point is indistinguishable by degree
      When I enumerate every point in a window
      Then every point reports 3 in-arrows and 3 out-arrows
      And no point reports a different degree from any other

    Scenario: Every point in a window reaches every other by forward movement
      When I follow out-arrows from the window's centre
      Then every point in the window is reachable
      And every point in the window can reach that centre

    Scenario Outline: A far-off cell is an ordinary cell
      Given the point at cell <cell>
      When I query its adjacency
      Then it has 3 in-arrows and 3 out-arrows
      And nothing about the answer differs from a cell near the origin

      Examples:
        | cell                    | note                        |
        | (0, 0)                  | the seed                    |
        | (1000, -1000)           | far out, and negative       |
        | (-99999, 99999)         | far enough to have been a rim |

  Rule: Generation is deterministic

    ADR 0001. A generator that varied would make every replay suspect, and
    ordering — not randomness — is the realistic way that happens. A stateless
    generator makes most of that unreachable, which is itself worth asserting.

    Scenario: Two generators agree exactly
      Given a second tiling generated by makeTiling
      When I take the same window from each
      Then their point sequences are identical in order
      And their arrow sequences are identical in order
      And their vertex sequences are identical in order

    Scenario: Query history does not change adjacency order
      Given a second tiling generated by makeTiling
      When I query many points' out-arrows on the first board
      And I query one of those points' out-arrows on the second board
      Then both boards return that point's out-arrows in the same order

    Scenario: The generator holds no state
      Given a generator that has already answered many queries
      When I take a window from it and the same window from a fresh generator
      Then the two are identical
      And the generator exposes no property that is not a method
      # There is no collection to iterate in the wrong order, so ADR 0001's
      # realistic determinism failure is unreachable by construction.
